version: "3.9"
services:
  api-auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: abcall-auth-api
    restart: always
    volumes:
      - ".:/app"
    ports:
      - "3004:3004"
    env_file:
      - .env
    tty: true